name: Terraform Automation

on:
  push:
    branches:
      - master

    steps:

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push' && github.event_ref == 'refs/heads/master'
      run: terraform apply -auto-approve



