name: Terraform Automation

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push' && github.event_ref == 'refs/heads/main'
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event_name == 'pull_request'
      run: terraform destroy -auto-approve

